// Seed the tickets collection.
db = db.getSiblingDB("enterprise");

if (db.tickets.countDocuments({}) > 0) {
  print("tickets already seeded (" + db.tickets.countDocuments({}) + " docs), skipping");
} else {
  const tickets = [
    { _id: "tkt-001", title: "MongoDB replica set election storm", body: "Customer cluster experiencing frequent primary elections under load.", status: "open",        priority: "p0", assignee_id: "emp-022", created_at: ISODate("2026-05-01"), tags: ["mongodb", "replication", "urgent"] },
    { _id: "tkt-002", title: "Slow query on tickets aggregation",   body: "Aggregation pipeline on tickets takes >10s on 50k rows.",                 status: "in_progress", priority: "p1", assignee_id: "emp-001", created_at: ISODate("2026-05-02"), tags: ["mongodb", "performance"] },
    { _id: "tkt-003", title: "Onboarding doc out of date",          body: "New-hire checklist still references the old VPN endpoint.",               status: "open",        priority: "p3", assignee_id: "emp-030", created_at: ISODate("2026-05-03"), tags: ["onboarding", "docs"] },
    { _id: "tkt-004", title: "API 502 spike Tuesday",               body: "Gateway returned 502s for ~4 minutes during deploy window.",              status: "resolved",    priority: "p1", assignee_id: "emp-004", created_at: ISODate("2026-04-22"), tags: ["api", "incident"] },
    { _id: "tkt-005", title: "Sales demo data refresh",             body: "Demo tenant needs fresh seed data ahead of Friday's pitch.",              status: "in_progress", priority: "p2", assignee_id: "emp-014", created_at: ISODate("2026-05-05"), tags: ["sales", "demo"] },
    { _id: "tkt-006", title: "Salary band review",                  body: "Annual review for IC4 band ranges across departments.",                   status: "open",        priority: "p2", assignee_id: "emp-030", created_at: ISODate("2026-05-06"), tags: ["hr", "policy"] },
    { _id: "tkt-007", title: "Recurring monthly invoice failure",   body: "Stripe webhook retries failing for tenant ACME-12.",                      status: "open",        priority: "p1", assignee_id: "emp-043", created_at: ISODate("2026-05-07"), tags: ["billing", "stripe"] },
    { _id: "tkt-008", title: "Add audit log retention policy",      body: "Define retention windows for security audit logs.",                       status: "in_progress", priority: "p2", assignee_id: "emp-007", created_at: ISODate("2026-04-28"), tags: ["security", "policy"] },
    { _id: "tkt-009", title: "Kubernetes node drain hangs",         body: "Node drain during upgrade hangs on a single pod with PDB=1.",             status: "resolved",    priority: "p1", assignee_id: "emp-004", created_at: ISODate("2026-04-18"), tags: ["k8s", "infra"] },
    { _id: "tkt-010", title: "Customer asks for SAML SSO",          body: "Enterprise prospect requires SAML before signing.",                       status: "open",        priority: "p2", assignee_id: "emp-010", created_at: ISODate("2026-05-09"), tags: ["sales", "auth"] },
    { _id: "tkt-011", title: "Web UI typo on settings page",        body: "Typo: 'Recieve' should be 'Receive'.",                                    status: "closed",      priority: "p3", assignee_id: "emp-006", created_at: ISODate("2026-04-15"), tags: ["ui", "typo"] },
    { _id: "tkt-012", title: "Backup restore test failure",         body: "Monthly DR drill failed to restore tickets collection cleanly.",          status: "open",        priority: "p0", assignee_id: "emp-022", created_at: ISODate("2026-05-10"), tags: ["backup", "dr", "urgent"] },
    { _id: "tkt-013", title: "Add structured logging",              body: "Replace ad-hoc print statements with structlog in mcp service.",          status: "open",        priority: "p3", assignee_id: "emp-008", created_at: ISODate("2026-05-11"), tags: ["observability"] },
    { _id: "tkt-014", title: "Hire two more support engineers",     body: "Plan headcount for 2026 Q3 support team.",                                status: "in_progress", priority: "p2", assignee_id: "emp-032", created_at: ISODate("2026-05-12"), tags: ["hiring", "hr"] },
    { _id: "tkt-015", title: "DSAR request from EU customer",       body: "GDPR data subject access request — 30-day SLA.",                          status: "open",        priority: "p1", assignee_id: "emp-030", created_at: ISODate("2026-05-13"), tags: ["gdpr", "compliance"] },
    { _id: "tkt-016", title: "Add rate limiting to MCP server",     body: "Per-session token bucket needed before public exposure.",                 status: "open",        priority: "p1", assignee_id: "emp-007", created_at: ISODate("2026-05-14"), tags: ["security", "mcp"] },
    { _id: "tkt-017", title: "Forecast model overfits Q1",          body: "Finance forecast model predicting too aggressively for Q1 2026.",         status: "in_progress", priority: "p2", assignee_id: "emp-040", created_at: ISODate("2026-05-04"), tags: ["finance", "forecasting"] },
    { _id: "tkt-018", title: "Documentation site 404 on /api",      body: "Public docs site returns 404 on /api index page.",                        status: "resolved",    priority: "p2", assignee_id: "emp-006", created_at: ISODate("2026-04-30"), tags: ["docs", "ui"] },
    { _id: "tkt-019", title: "Customer requests bulk export",       body: "Customer wants nightly CSV export of their tickets.",                     status: "open",        priority: "p3", assignee_id: "emp-020", created_at: ISODate("2026-05-15"), tags: ["feature", "export"] },
    { _id: "tkt-020", title: "ML inference latency p99 too high",   body: "Inference p99 latency 1.2s, target 400ms.",                                status: "in_progress", priority: "p1", assignee_id: "emp-009", created_at: ISODate("2026-05-08"), tags: ["ml", "performance"] },
    { _id: "tkt-021", title: "Build pipeline flaky on integration", body: "Integration test stage fails ~20% of the time without code changes.",     status: "open",        priority: "p2", assignee_id: "emp-008", created_at: ISODate("2026-05-16"), tags: ["ci", "flake"] },
    { _id: "tkt-022", title: "VP Sales pipeline review",            body: "Quarterly pipeline review with VP Sales next week.",                       status: "in_progress", priority: "p3", assignee_id: "emp-011", created_at: ISODate("2026-05-06"), tags: ["sales", "meeting"] },
    { _id: "tkt-023", title: "Tax filing prep for Q2",              body: "Gather expense reports for Q2 tax filings.",                              status: "open",        priority: "p2", assignee_id: "emp-043", created_at: ISODate("2026-05-17"), tags: ["finance", "tax"] },
    { _id: "tkt-024", title: "Support runbook for replica election", body: "Runbook needed for MongoDB primary election storms.",                     status: "open",        priority: "p2", assignee_id: "emp-021", created_at: ISODate("2026-05-18"), tags: ["runbook", "mongodb"] },
    { _id: "tkt-025", title: "Customer churn risk: ACME-12",        body: "ACME-12 churn risk flagged by NPS dip and billing issues.",               status: "in_progress", priority: "p1", assignee_id: "emp-010", created_at: ISODate("2026-05-13"), tags: ["sales", "retention"] },
    { _id: "tkt-026", title: "Test coverage below 60% in mcp",      body: "Drive coverage in mcp service back above 80%.",                            status: "open",        priority: "p3", assignee_id: "emp-001", created_at: ISODate("2026-05-19"), tags: ["testing", "quality"] },
    { _id: "tkt-027", title: "GDPR DPO contact update",             body: "Update DPO contact in public privacy policy.",                            status: "closed",      priority: "p3", assignee_id: "emp-030", created_at: ISODate("2026-04-12"), tags: ["gdpr", "policy"] },
    { _id: "tkt-028", title: "ZX-13 prospect security questionnaire", body: "Complete security questionnaire for ZX-13 enterprise prospect.",         status: "in_progress", priority: "p2", assignee_id: "emp-014", created_at: ISODate("2026-05-11"), tags: ["sales", "security"] },
    { _id: "tkt-029", title: "Re-platform marketing site",          body: "Move marketing site to Next.js.",                                          status: "open",        priority: "p3", assignee_id: "emp-006", created_at: ISODate("2026-05-20"), tags: ["marketing", "web"] },
    { _id: "tkt-030", title: "Pager fatigue review",                body: "Review pager volume per oncall engineer for last 90 days.",                status: "open",        priority: "p2", assignee_id: "emp-021", created_at: ISODate("2026-05-18"), tags: ["oncall", "process"] },
    { _id: "tkt-031", title: "Encrypt backups at rest",             body: "Move backups from S3 SSE-S3 to SSE-KMS.",                                  status: "in_progress", priority: "p1", assignee_id: "emp-022", created_at: ISODate("2026-05-09"), tags: ["security", "backup"] },
    { _id: "tkt-032", title: "Recurring weekly sync canceled?",     body: "Engineering/Support weekly sync — should we still hold it?",               status: "closed",      priority: "p3", assignee_id: "emp-021", created_at: ISODate("2026-04-08"), tags: ["process", "meeting"] },
    { _id: "tkt-033", title: "Hire a sales engineer for EMEA",      body: "Open req for EMEA sales engineer; coordinate with recruiting.",            status: "open",        priority: "p2", assignee_id: "emp-032", created_at: ISODate("2026-05-15"), tags: ["hiring", "sales"] },
    { _id: "tkt-034", title: "Onboarding portal access broken",     body: "New hires can't log in to the onboarding portal on day one.",              status: "resolved",    priority: "p1", assignee_id: "emp-030", created_at: ISODate("2026-04-25"), tags: ["onboarding", "auth"] },
    { _id: "tkt-035", title: "Add chargeback tracking dashboard",   body: "Finance team wants weekly chargeback metrics.",                            status: "open",        priority: "p3", assignee_id: "emp-040", created_at: ISODate("2026-05-19"), tags: ["finance", "metrics"] },
    { _id: "tkt-036", title: "Stripe webhook idempotency bug",      body: "Duplicate webhooks creating duplicate invoice rows.",                      status: "in_progress", priority: "p0", assignee_id: "emp-005", created_at: ISODate("2026-05-17"), tags: ["billing", "stripe", "urgent"] },
    { _id: "tkt-037", title: "Recurring out-of-disk on staging",    body: "Staging cluster runs out of disk every ~3 weeks.",                         status: "open",        priority: "p2", assignee_id: "emp-024", created_at: ISODate("2026-05-12"), tags: ["infra", "staging"] },
    { _id: "tkt-038", title: "Improve search relevance ranking",    body: "Tune search relevance using click-through data.",                          status: "in_progress", priority: "p3", assignee_id: "emp-009", created_at: ISODate("2026-05-14"), tags: ["search", "ml"] },
    { _id: "tkt-039", title: "VPN slow for remote engineers",       body: "EU-based engineers report VPN latency >300ms.",                            status: "open",        priority: "p2", assignee_id: "emp-004", created_at: ISODate("2026-05-19"), tags: ["infra", "vpn"] },
    { _id: "tkt-040", title: "Budget reforecast May",               body: "Mid-May reforecast against actuals.",                                       status: "in_progress", priority: "p2", assignee_id: "emp-041", created_at: ISODate("2026-05-20"), tags: ["finance", "forecast"] },
  ];

  db.tickets.insertMany(tickets);
  print("inserted " + tickets.length + " tickets");
}
