"""Stage 18 — architecture graph v2.

Builds a `{layers, nodes, edges, flows, concerns}` graph for the Architecture
page v2. This is a richer model than topology.py (Stage 12): it adds boundary
boxes (layers), directed edges with integration metadata, named flows, and
explicit visual lanes.

No live calls — all data is static placeholder (TBD sentinel for unknown infra).
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Layers — boundary boxes (environments / accounts / VPCs)
# parent_id: null  →  top-level; non-null  →  nested inside that parent layer
# ---------------------------------------------------------------------------
LAYERS: list[dict[str, Any]] = [
    {
        "id": "on-prem",
        "label": "On-Premises Zone",
        "kind": "on_prem_zone",
        "parent_id": None,
        "meta": {
            "account_id": "TBD",
            "subscription_id": "TBD",
            "project_id": "TBD",
            "region": "TBD",
            "vpc_id": "TBD",
            "subnet_id": "TBD",
            "cidr": "TBD",
            "security_groups": "TBD",
            "owner": "TBD",
            "data_classification": "confidential",
            "criticality": "tier-1",
        },
    },
    {
        "id": "aws-prod",
        "label": "AWS — Production",
        "kind": "aws_account",
        "parent_id": None,
        "meta": {
            "account_id": "TBD",
            "subscription_id": "TBD",
            "project_id": "TBD",
            "region": "TBD",
            "vpc_id": "TBD",
            "subnet_id": "TBD",
            "cidr": "TBD",
            "security_groups": "TBD",
            "owner": "TBD",
            "data_classification": "confidential",
            "criticality": "tier-1",
        },
    },
    {
        "id": "aws-prod-vpc",
        "label": "AWS Prod — VPC",
        "kind": "aws_account",
        "parent_id": "aws-prod",
        "meta": {
            "account_id": "TBD",
            "subscription_id": "TBD",
            "project_id": "TBD",
            "region": "TBD",
            "vpc_id": "TBD",
            "subnet_id": "TBD",
            "cidr": "TBD",
            "security_groups": "TBD",
            "owner": "TBD",
            "data_classification": "confidential",
            "criticality": "tier-1",
        },
    },
    {
        "id": "aws-nonprod",
        "label": "AWS — Non-Production",
        "kind": "aws_account",
        "parent_id": None,
        "meta": {
            "account_id": "TBD",
            "subscription_id": "TBD",
            "project_id": "TBD",
            "region": "TBD",
            "vpc_id": "TBD",
            "subnet_id": "TBD",
            "cidr": "TBD",
            "security_groups": "TBD",
            "owner": "TBD",
            "data_classification": "internal",
            "criticality": "tier-2",
        },
    },
    {
        "id": "azure-sub",
        "label": "Azure — Primary Subscription",
        "kind": "azure_subscription",
        "parent_id": None,
        "meta": {
            "account_id": "TBD",
            "subscription_id": "TBD",
            "project_id": "TBD",
            "region": "TBD",
            "vpc_id": "TBD",
            "subnet_id": "TBD",
            "cidr": "TBD",
            "security_groups": "TBD",
            "owner": "TBD",
            "data_classification": "confidential",
            "criticality": "tier-2",
        },
    },
    {
        "id": "gcp-proj",
        "label": "GCP — Primary Project",
        "kind": "gcp_project",
        "parent_id": None,
        "meta": {
            "account_id": "TBD",
            "subscription_id": "TBD",
            "project_id": "TBD",
            "region": "TBD",
            "vpc_id": "TBD",
            "subnet_id": "TBD",
            "cidr": "TBD",
            "security_groups": "TBD",
            "owner": "TBD",
            "data_classification": "internal",
            "criticality": "tier-2",
        },
    },
    {
        "id": "saas",
        "label": "SaaS Platforms",
        "kind": "saas",
        "parent_id": None,
        "meta": {
            "account_id": "TBD",
            "subscription_id": "TBD",
            "project_id": "TBD",
            "region": "TBD",
            "vpc_id": "TBD",
            "subnet_id": "TBD",
            "cidr": "TBD",
            "security_groups": "TBD",
            "owner": "TBD",
            "data_classification": "internal",
            "criticality": "tier-1",
        },
    },
]

# ---------------------------------------------------------------------------
# Nodes — systems / services
# lane: visual column left→right:
#   sources | risk_itsm | atlassian | implementation |
#   warehouse_observability | artifacts
# ---------------------------------------------------------------------------
NODES: list[dict[str, Any]] = [
    # ---- sources lane -------------------------------------------------------
    {
        "id": "onprem-log-shipper",
        "label": "On-Prem Log Shipper",
        "kind": "cloud",
        "layer_id": "on-prem",
        "status": "healthy",
        "lane": "sources",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "confidential",
            "criticality": "tier-1",
            "runbook_slug": "runbooks/log-shipper-onprem",
        },
        "concerns": [],
    },
    {
        "id": "aws-log-source",
        "label": "AWS CloudTrail / VPC Flow Logs",
        "kind": "cloud",
        "layer_id": "aws-prod",
        "status": "healthy",
        "lane": "sources",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "confidential",
            "criticality": "tier-1",
            "runbook_slug": "TBD",
        },
        "concerns": [],
    },
    {
        "id": "azure-log-source",
        "label": "Azure Monitor / Activity Logs",
        "kind": "cloud",
        "layer_id": "azure-sub",
        "status": "healthy",
        "lane": "sources",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "confidential",
            "criticality": "tier-2",
            "runbook_slug": "TBD",
        },
        "concerns": [],
    },
    {
        "id": "gcp-log-source",
        "label": "GCP Cloud Logging",
        "kind": "cloud",
        "layer_id": "gcp-proj",
        "status": "healthy",
        "lane": "sources",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "internal",
            "criticality": "tier-2",
            "runbook_slug": "TBD",
        },
        "concerns": [],
    },
    # ---- risk_itsm lane -----------------------------------------------------
    {
        "id": "archer",
        "label": "Archer (RIMS)",
        "kind": "shield",
        "layer_id": "saas",
        "status": "healthy",
        "lane": "risk_itsm",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "confidential",
            "criticality": "tier-1",
            "runbook_slug": "runbooks/archer-connector",
        },
        "concerns": [],
    },
    {
        "id": "servicenow",
        "label": "ServiceNow (SNOW)",
        "kind": "ticket",
        "layer_id": "saas",
        "status": "healthy",
        "lane": "risk_itsm",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "confidential",
            "criticality": "tier-1",
            "runbook_slug": "runbooks/servicenow-connector",
        },
        "concerns": [],
    },
    # ---- atlassian lane -----------------------------------------------------
    {
        "id": "jira",
        "label": "Jira",
        "kind": "kanban",
        "layer_id": "saas",
        "status": "healthy",
        "lane": "atlassian",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "internal",
            "criticality": "tier-1",
            "runbook_slug": "runbooks/jira-connector",
        },
        "concerns": [],
    },
    {
        "id": "confluence",
        "label": "Confluence",
        "kind": "book",
        "layer_id": "saas",
        "status": "healthy",
        "lane": "atlassian",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "internal",
            "criticality": "tier-1",
            "runbook_slug": "runbooks/confluence-connector",
        },
        "concerns": [],
    },
    # ---- implementation lane ------------------------------------------------
    {
        "id": "github",
        "label": "GitHub",
        "kind": "git",
        "layer_id": "saas",
        "status": "healthy",
        "lane": "implementation",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "internal",
            "criticality": "tier-1",
            "runbook_slug": "runbooks/github-connector",
        },
        "concerns": [],
    },
    {
        "id": "cicd-deploy",
        "label": "CI/CD Deploy Pipeline",
        "kind": "cloud",
        "layer_id": "aws-nonprod",
        "status": "healthy",
        "lane": "implementation",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "internal",
            "criticality": "tier-2",
            "runbook_slug": "runbooks/cicd-pipeline",
        },
        "concerns": [],
    },
    {
        "id": "agentic-worker",
        "label": "Agentic Workflow Workers",
        "kind": "cloud",
        "layer_id": "aws-prod-vpc",
        "status": "planned",
        "lane": "implementation",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "confidential",
            "criticality": "tier-1",
            "runbook_slug": "runbooks/agentic-workers",
        },
        "concerns": [],
    },
    # ---- warehouse_observability lane ---------------------------------------
    {
        "id": "ec2-mongo-wh",
        "label": "MongoDB Warehouse",
        "kind": "ec2_mongodb",
        "layer_id": "aws-prod-vpc",
        "status": "healthy",
        "lane": "warehouse_observability",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "restricted",
            "criticality": "tier-1",
            "runbook_slug": "runbooks/mongodb-warehouse",
        },
        "concerns": [],
    },
    {
        "id": "snowflake",
        "label": "Snowflake Analytics",
        "kind": "snowflake",
        "layer_id": "saas",
        "status": "healthy",
        "lane": "warehouse_observability",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "confidential",
            "criticality": "tier-1",
            "runbook_slug": "runbooks/snowflake-connector",
        },
        "concerns": [],
    },
    {
        "id": "observability",
        "label": "Observability / Log Ingest",
        "kind": "observability",
        "layer_id": "aws-prod-vpc",
        "status": "healthy",
        "lane": "warehouse_observability",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "confidential",
            "criticality": "tier-1",
            "runbook_slug": "runbooks/observability-platform",
        },
        "concerns": [],
    },
    # ---- artifacts lane -----------------------------------------------------
    {
        "id": "report-gen",
        "label": "PDF / PPT Report Generator",
        "kind": "artifact",
        "layer_id": "aws-prod-vpc",
        "status": "healthy",
        "lane": "artifacts",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "confidential",
            "criticality": "tier-1",
            "runbook_slug": "runbooks/report-generator",
        },
        "concerns": [],
    },
    {
        "id": "audit-packet",
        "label": "Audit Packet Store",
        "kind": "s3",
        "layer_id": "aws-prod",
        "status": "healthy",
        "lane": "artifacts",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "restricted",
            "criticality": "tier-1",
            "runbook_slug": "runbooks/audit-packet-store",
        },
        "concerns": [],
    },
    {
        "id": "confluence-pub",
        "label": "Confluence Public Docs",
        "kind": "book",
        "layer_id": "saas",
        "status": "healthy",
        "lane": "artifacts",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "internal",
            "criticality": "tier-2",
            "runbook_slug": "TBD",
        },
        "concerns": [],
    },
    {
        "id": "jira-updates",
        "label": "Jira Status Updates",
        "kind": "kanban",
        "layer_id": "saas",
        "status": "planned",
        "lane": "artifacts",
        "meta": {
            "hostname": "TBD",
            "private_ip": "TBD",
            "public_url": "TBD",
            "instance_type": "TBD",
            "storage_gb": "TBD",
            "retention_days": "TBD",
            "owner": "TBD",
            "data_classification": "internal",
            "criticality": "tier-2",
            "runbook_slug": "TBD",
        },
        "concerns": [],
    },
]

# ---------------------------------------------------------------------------
# Edges — directed integrations
# flow: id of a Flow this edge belongs to, or null
# planned: True = not yet built; False = live
# ---------------------------------------------------------------------------
EDGES: list[dict[str, Any]] = [
    # ---------- canonical risk_to_artifact flow edges -----------------------
    {
        "from": "archer",
        "to": "servicenow",
        "label": "finding → incident",
        "protocol": "REST",
        "flow": "risk_to_artifact",
        "planned": False,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "TBD",
            "sla": "TBD",
            "agentic_status": "current",
        },
    },
    {
        "from": "servicenow",
        "to": "jira",
        "label": "finding → epic/ticket",
        "protocol": "REST",
        "flow": "risk_to_artifact",
        "planned": False,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "TBD",
            "sla": "TBD",
            "agentic_status": "current",
        },
    },
    {
        "from": "archer",
        "to": "jira",
        "label": "risk finding → Jira epic",
        "protocol": "REST",
        "flow": "risk_to_artifact",
        "planned": False,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "TBD",
            "sla": "TBD",
            "agentic_status": "current",
        },
    },
    {
        "from": "jira",
        "to": "confluence",
        "label": "epic → epic-log doc",
        "protocol": "REST",
        "flow": "risk_to_artifact",
        "planned": False,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "TBD",
            "sla": "TBD",
            "agentic_status": "current",
        },
    },
    {
        "from": "jira",
        "to": "github",
        "label": "ticket → branch/PR",
        "protocol": "webhook",
        "flow": "risk_to_artifact",
        "planned": False,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "event-driven",
            "sla": "TBD",
            "agentic_status": "current",
        },
    },
    {
        "from": "github",
        "to": "cicd-deploy",
        "label": "PR merge → deploy",
        "protocol": "webhook",
        "flow": "risk_to_artifact",
        "planned": False,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "event-driven",
            "sla": "TBD",
            "agentic_status": "current",
        },
    },
    {
        "from": "github",
        "to": "ec2-mongo-wh",
        "label": "PR records → warehouse",
        "protocol": "agent workflow",
        "flow": "risk_to_artifact",
        "planned": True,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "TBD",
            "sla": "TBD",
            "agentic_status": "planned",
        },
    },
    {
        "from": "ec2-mongo-wh",
        "to": "observability",
        "label": "warehouse → observability",
        "protocol": "log shipper",
        "flow": "risk_to_artifact",
        "planned": False,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "TBD",
            "sla": "TBD",
            "agentic_status": "current",
        },
    },
    {
        "from": "ec2-mongo-wh",
        "to": "snowflake",
        "label": "evidence → analytics",
        "protocol": "SQL/export",
        "flow": "risk_to_artifact",
        "planned": False,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "TBD",
            "sla": "TBD",
            "agentic_status": "current",
        },
    },
    {
        "from": "ec2-mongo-wh",
        "to": "report-gen",
        "label": "evidence → report",
        "protocol": "REST",
        "flow": "risk_to_artifact",
        "planned": False,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "TBD",
            "sla": "TBD",
            "agentic_status": "current",
        },
    },
    {
        "from": "report-gen",
        "to": "audit-packet",
        "label": "report → audit packet",
        "protocol": "REST",
        "flow": "risk_to_artifact",
        "planned": False,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "TBD",
            "sla": "TBD",
            "agentic_status": "current",
        },
    },
    {
        "from": "report-gen",
        "to": "confluence-pub",
        "label": "report → public docs",
        "protocol": "REST",
        "flow": "risk_to_artifact",
        "planned": True,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "TBD",
            "sla": "TBD",
            "agentic_status": "planned",
        },
    },
    {
        "from": "agentic-worker",
        "to": "jira-updates",
        "label": "agent → Jira status",
        "protocol": "agent workflow",
        "flow": "risk_to_artifact",
        "planned": True,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "event-driven",
            "sla": "TBD",
            "agentic_status": "planned",
        },
    },
    # ---------- log-shipper edges from each environment into warehouse -------
    {
        "from": "onprem-log-shipper",
        "to": "ec2-mongo-wh",
        "label": "on-prem logs → warehouse",
        "protocol": "log shipper",
        "flow": None,
        "planned": False,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "TBD",
            "sla": "TBD",
            "agentic_status": "current",
        },
    },
    {
        "from": "aws-log-source",
        "to": "ec2-mongo-wh",
        "label": "AWS logs → warehouse",
        "protocol": "log shipper",
        "flow": None,
        "planned": False,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "TBD",
            "sla": "TBD",
            "agentic_status": "current",
        },
    },
    {
        "from": "azure-log-source",
        "to": "ec2-mongo-wh",
        "label": "Azure logs → warehouse",
        "protocol": "log shipper",
        "flow": None,
        "planned": False,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "TBD",
            "sla": "TBD",
            "agentic_status": "current",
        },
    },
    {
        "from": "gcp-log-source",
        "to": "ec2-mongo-wh",
        "label": "GCP logs → warehouse",
        "protocol": "log shipper",
        "flow": None,
        "planned": False,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "TBD",
            "sla": "TBD",
            "agentic_status": "current",
        },
    },
    # ---------- warehouse record-of-record ingest from ITSM/Atlassian --------
    {
        "from": "servicenow",
        "to": "ec2-mongo-wh",
        "label": "findings (SoR) → warehouse",
        "protocol": "REST",
        "flow": None,
        "planned": False,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "TBD",
            "sla": "TBD",
            "agentic_status": "current",
        },
    },
    {
        "from": "jira",
        "to": "ec2-mongo-wh",
        "label": "work items (SoR) → warehouse",
        "protocol": "REST",
        "flow": None,
        "planned": False,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "TBD",
            "sla": "TBD",
            "agentic_status": "current",
        },
    },
    {
        "from": "confluence",
        "to": "ec2-mongo-wh",
        "label": "doc records (SoR) → warehouse",
        "protocol": "REST",
        "flow": None,
        "planned": False,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "TBD",
            "sla": "TBD",
            "agentic_status": "current",
        },
    },
    # ---------- agentic MCP tool edges (planned) ----------------------------
    {
        "from": "agentic-worker",
        "to": "ec2-mongo-wh",
        "label": "agent writes evidence",
        "protocol": "MCP tool",
        "flow": None,
        "planned": True,
        "integration": {
            "direction": "bidirectional",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "event-driven",
            "sla": "TBD",
            "agentic_status": "planned",
        },
    },
    {
        "from": "agentic-worker",
        "to": "archer",
        "label": "agent reads findings",
        "protocol": "MCP tool",
        "flow": None,
        "planned": True,
        "integration": {
            "direction": "one-way",
            "auth_mode": "TBD",
            "endpoint_ref": "TBD",
            "frequency": "event-driven",
            "sla": "TBD",
            "agentic_status": "planned",
        },
    },
]

# ---------------------------------------------------------------------------
# Flows — named end-to-end workflows
# steps: ordered list of node_ids the flow passes through
# ---------------------------------------------------------------------------
FLOWS: list[dict[str, Any]] = [
    {
        "id": "risk_to_artifact",
        "label": "Risk to artifact",
        "steps": [
            "archer",
            "servicenow",
            "jira",
            "confluence",
            "github",
            "cicd-deploy",
            "ec2-mongo-wh",
            "observability",
            "snowflake",
            "report-gen",
            "audit-packet",
            "confluence-pub",
        ],
    },
    {
        "id": "log_ingest",
        "label": "Log ingest (all environments)",
        "steps": [
            "onprem-log-shipper",
            "aws-log-source",
            "azure-log-source",
            "gcp-log-source",
            "ec2-mongo-wh",
        ],
    },
    {
        "id": "agentic_evidence",
        "label": "Agentic evidence workflow (planned)",
        "steps": [
            "agentic-worker",
            "archer",
            "ec2-mongo-wh",
            "jira-updates",
        ],
    },
]

# ---------------------------------------------------------------------------
# Concerns — known issues / weak spots surfaced in the UI
# severity ∈ {critical, high, medium, low}
# kind: short machine tag
# link: /hub#<anchor> style, matching topology.py convention
# ---------------------------------------------------------------------------
CONCERNS: list[dict[str, Any]] = [
    {
        "id": "aws:rds-prod-audit-logging",
        "severity": "critical",
        "kind": "logging_disabled",
        "title": "Prod RDS audit logging DISABLED — evidence gap in AWS prod",
        "node_id": "aws-log-source",
        "link": "/hub#aws",
    },
    {
        "id": "snow:p1-open",
        "severity": "critical",
        "kind": "p1_incident",
        "title": "P1 incident open in ServiceNow — SLA breach risk",
        "node_id": "servicenow",
        "link": "/hub#servicenow",
    },
    {
        "id": "mongo:retention-tbd",
        "severity": "medium",
        "kind": "config_unknown",
        "title": "MongoDB Warehouse retention_days is TBD — audit trail completeness unverified",
        "node_id": "ec2-mongo-wh",
        "link": "/hub#mongodb",
    },
]

# Attach concern ids onto node.concerns lists
_CONCERN_INDEX: dict[str, list[str]] = {}
for _c in CONCERNS:
    _nid = _c.get("node_id", "")
    if _nid:
        _CONCERN_INDEX.setdefault(_nid, []).append(_c["id"])

for _n in NODES:
    _n["concerns"] = _CONCERN_INDEX.get(_n["id"], [])


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
async def build_architecture() -> dict[str, Any]:
    """Return the v2 architecture graph (no live calls; pure mock/placeholder).

    Keys: layers, nodes, edges, flows, concerns.
    """
    # Stable severity ordering for the concern list.
    _rank = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    sorted_concerns = sorted(
        CONCERNS, key=lambda c: _rank.get(c.get("severity", "low"), 9)
    )

    return {
        "layers": LAYERS,
        "nodes": NODES,
        "edges": EDGES,
        "flows": FLOWS,
        "concerns": sorted_concerns,
    }
